#pragma once
#include <stdint.h>

typedef enum
{
AST_TOKEN_UNKNOWN,
AST_TOKEN_EOF,
AST_TOKEN_WHITESPACE,
AST_TOKEN_BLOCK_OPEN,
AST_TOKEN_BLOCK_CLOSE,
AST_TOKEN_EXP_OPEN,
AST_TOKEN_EXP_CLOSE,
AST_TOKEN_STATEMENT_TERMINATOR,
AST_TOKEN_IF,
AST_TOKEN_ELSE,
AST_TOKEN_ELSEIF,
AST_TOKEN_NUMBER,
AST_TOKEN_EQUAL,
AST_TOKEN_ID,
AST_TOKEN_COUNT
} ast_token_t;


ast_token_t ast_get_token(char const ** out_p, char buf[], int32_t buflen);