#pragma once
#include <stdint.h>

//https://github.com/nothings/stb/blob/master/stb_c_lexer.h

typedef enum
{
TOKEN_CONSTANT_UNKNOWN,
TOKEN_CONSTANT_EOF,
TOKEN_CONSTANT_WHITESPACE,
TOKEN_CONSTANT_BLOCK_OPEN,
TOKEN_CONSTANT_BLOCK_CLOSE,
TOKEN_CONSTANT_EXP_OPEN,
TOKEN_CONSTANT_EXP_CLOSE,
TOKEN_CONSTANT_STATEMENT_TERMINATOR,
TOKEN_CONSTANT_IF,
TOKEN_CONSTANT_ELSE,
TOKEN_CONSTANT_ELSEIF,
TOKEN_CONSTANT_NUMBER,
TOKEN_CONSTANT_EQUAL,
TOKEN_CONSTANT_PLUS,
TOKEN_CONSTANT_MINUS,
TOKEN_CONSTANT_MUL,
TOKEN_CONSTANT_DIV,
TOKEN_CONSTANT_ID,
TOKEN_CONSTANT_COUNT
} token_constant_t;



static int32_t tokens_precedence[] = 
{
	[TOKEN_CONSTANT_NUMBER] = 0,
	[TOKEN_CONSTANT_ID] = 0,
	[TOKEN_CONSTANT_EQUAL] = 14,
	[TOKEN_CONSTANT_PLUS] = 2,
	[TOKEN_CONSTANT_MINUS] = 2,
	[TOKEN_CONSTANT_MUL] = 3,
	[TOKEN_CONSTANT_DIV] = 3,
	[TOKEN_CONSTANT_COUNT] = 0
};


char const * token_constant_t_tostr(token_constant_t token);
int32_t token_constant_t_tolen(token_constant_t token);