#pragma once
// Generated CAN-ids
#define CANID_RC0_C0123                          0x0C8
#define CANID_RC0_C4567                          0x0C9
#define CANID_RC0_C89                            0x0CA
#define CANID_DJMIX_MOVE                         0x00A
#define CANID_ODRIVE1_GET_VERSION                0x020
#define CANID_ODRIVE1_HEARTBEAT                  0x021
#define CANID_ODRIVE1_ESTOP                      0x022
#define CANID_ODRIVE1_GET_ERROR                  0x023
#define CANID_ODRIVE1_RXSDO                      0x024
#define CANID_ODRIVE1_TXSDO                      0x025
#define CANID_ODRIVE1_ADDRESS                    0x026
#define CANID_ODRIVE1_SET_AXIS_STATE             0x027
#define CANID_ODRIVE1_GET_ENCODER_ESTIMATES      0x029
#define CANID_ODRIVE1_SET_CONTROLLER_MODE        0x02B
#define CANID_ODRIVE1_SET_INPUT_POS              0x02C
#define CANID_ODRIVE1_SET_INPUT_VEL              0x02D
#define CANID_ODRIVE1_SET_INPUT_TORQUE           0x02E
#define CANID_ODRIVE1_SET_LIMITS                 0x02F
#define CANID_ODRIVE1_SET_TRAJ_VEL_LIMITS        0x031
#define CANID_ODRIVE1_SET_TRAJ_ACCEL_LIMITS      0x032
#define CANID_ODRIVE1_SET_TRAJ_INERTIA           0x033
#define CANID_ODRIVE1_GET_IQ                     0x034
#define CANID_ODRIVE1_GET_TEMPERATURE            0x035
#define CANID_ODRIVE1_REBOOT                     0x036
#define CANID_ODRIVE1_GET_BUS_VOLTAGE_CURRENT    0x037
#define CANID_ODRIVE1_CLEAR_ERRORS               0x038
#define CANID_ODRIVE1_SET_ABSOLUTE_POSITION      0x039
#define CANID_ODRIVE1_SET_POS_GAINS              0x03A
#define CANID_ODRIVE1_SET_VEL_GAINS              0x03B
#define CANID_ODRIVE1_GET_TORQUES                0x03C
#define CANID_ODRIVE1_GET_POWERS                 0x03D
#define CANID_ODRIVE2_GET_VERSION                0x040
#define CANID_ODRIVE2_HEARTBEAT                  0x041
#define CANID_ODRIVE2_ESTOP                      0x042
#define CANID_ODRIVE2_GET_ERROR                  0x043
#define CANID_ODRIVE2_RXSDO                      0x044
#define CANID_ODRIVE2_TXSDO                      0x045
#define CANID_ODRIVE2_ADDRESS                    0x046
#define CANID_ODRIVE2_SET_AXIS_STATE             0x047
#define CANID_ODRIVE2_GET_ENCODER_ESTIMATES      0x049
#define CANID_ODRIVE2_SET_CONTROLLER_MODE        0x04B
#define CANID_ODRIVE2_SET_INPUT_POS              0x04C
#define CANID_ODRIVE2_SET_INPUT_VEL              0x04D
#define CANID_ODRIVE2_SET_INPUT_TORQUE           0x04E
#define CANID_ODRIVE2_SET_LIMITS                 0x04F
#define CANID_ODRIVE2_SET_TRAJ_VEL_LIMITS        0x051
#define CANID_ODRIVE2_SET_TRAJ_ACCEL_LIMITS      0x052
#define CANID_ODRIVE2_SET_TRAJ_INERTIA           0x053
#define CANID_ODRIVE2_GET_IQ                     0x054
#define CANID_ODRIVE2_GET_TEMPERATURE            0x055
#define CANID_ODRIVE2_REBOOT                     0x056
#define CANID_ODRIVE2_GET_BUS_VOLTAGE_CURRENT    0x057
#define CANID_ODRIVE2_CLEAR_ERRORS               0x058
#define CANID_ODRIVE2_SET_ABSOLUTE_POSITION      0x059
#define CANID_ODRIVE2_SET_POS_GAINS              0x05A
#define CANID_ODRIVE2_SET_VEL_GAINS              0x05B
#define CANID_ODRIVE2_GET_TORQUES                0x05C
#define CANID_ODRIVE2_GET_POWERS                 0x05D
#define CANID_ODRIVE3_GET_VERSION                0x060
#define CANID_ODRIVE3_HEARTBEAT                  0x061
#define CANID_ODRIVE3_ESTOP                      0x062
#define CANID_ODRIVE3_GET_ERROR                  0x063
#define CANID_ODRIVE3_RXSDO                      0x064
#define CANID_ODRIVE3_TXSDO                      0x065
#define CANID_ODRIVE3_ADDRESS                    0x066
#define CANID_ODRIVE3_SET_AXIS_STATE             0x067
#define CANID_ODRIVE3_GET_ENCODER_ESTIMATES      0x069
#define CANID_ODRIVE3_SET_CONTROLLER_MODE        0x06B
#define CANID_ODRIVE3_SET_INPUT_POS              0x06C
#define CANID_ODRIVE3_SET_INPUT_VEL              0x06D
#define CANID_ODRIVE3_SET_INPUT_TORQUE           0x06E
#define CANID_ODRIVE3_SET_LIMITS                 0x06F
#define CANID_ODRIVE3_SET_TRAJ_VEL_LIMITS        0x071
#define CANID_ODRIVE3_SET_TRAJ_ACCEL_LIMITS      0x072
#define CANID_ODRIVE3_SET_TRAJ_INERTIA           0x073
#define CANID_ODRIVE3_GET_IQ                     0x074
#define CANID_ODRIVE3_GET_TEMPERATURE            0x075
#define CANID_ODRIVE3_REBOOT                     0x076
#define CANID_ODRIVE3_GET_BUS_VOLTAGE_CURRENT    0x077
#define CANID_ODRIVE3_CLEAR_ERRORS               0x078
#define CANID_ODRIVE3_SET_ABSOLUTE_POSITION      0x079
#define CANID_ODRIVE3_SET_POS_GAINS              0x07A
#define CANID_ODRIVE3_SET_VEL_GAINS              0x07B
#define CANID_ODRIVE3_GET_TORQUES                0x07C
#define CANID_ODRIVE3_GET_POWERS                 0x07D
#define CANID_ODRIVE4_GET_VERSION                0x080
#define CANID_ODRIVE4_HEARTBEAT                  0x081
#define CANID_ODRIVE4_ESTOP                      0x082
#define CANID_ODRIVE4_GET_ERROR                  0x083
#define CANID_ODRIVE4_RXSDO                      0x084
#define CANID_ODRIVE4_TXSDO                      0x085
#define CANID_ODRIVE4_ADDRESS                    0x086
#define CANID_ODRIVE4_SET_AXIS_STATE             0x087
#define CANID_ODRIVE4_GET_ENCODER_ESTIMATES      0x089
#define CANID_ODRIVE4_SET_CONTROLLER_MODE        0x08B
#define CANID_ODRIVE4_SET_INPUT_POS              0x08C
#define CANID_ODRIVE4_SET_INPUT_VEL              0x08D
#define CANID_ODRIVE4_SET_INPUT_TORQUE           0x08E
#define CANID_ODRIVE4_SET_LIMITS                 0x08F
#define CANID_ODRIVE4_SET_TRAJ_VEL_LIMITS        0x091
#define CANID_ODRIVE4_SET_TRAJ_ACCEL_LIMITS      0x092
#define CANID_ODRIVE4_SET_TRAJ_INERTIA           0x093
#define CANID_ODRIVE4_GET_IQ                     0x094
#define CANID_ODRIVE4_GET_TEMPERATURE            0x095
#define CANID_ODRIVE4_REBOOT                     0x096
#define CANID_ODRIVE4_GET_BUS_VOLTAGE_CURRENT    0x097
#define CANID_ODRIVE4_CLEAR_ERRORS               0x098
#define CANID_ODRIVE4_SET_ABSOLUTE_POSITION      0x099
#define CANID_ODRIVE4_SET_POS_GAINS              0x09A
#define CANID_ODRIVE4_SET_VEL_GAINS              0x09B
#define CANID_ODRIVE4_GET_TORQUES                0x09C
#define CANID_ODRIVE4_GET_POWERS                 0x09D
#define CANID_FUNKYBOT_SENSE                     0x014
#define CANID_AUTOPILOT_NAV                      0x015
#define CANID_VISION_POS                         0x002
#define CANID_VISION_VEL                         0x003
