#include "EgVkPhysicaldevicefeatures.h"
#include "EgTypes.h"
#include <stdio.h>



// https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceFeatures.html
ECS_DECLARE(EgVkPhysicalDeviceFeature_robustBufferAccess);
ECS_DECLARE(EgVkPhysicalDeviceFeature_fullDrawIndexUint32);
ECS_DECLARE(EgVkPhysicalDeviceFeature_imageCubeArray);
ECS_DECLARE(EgVkPhysicalDeviceFeature_independentBlend);
ECS_DECLARE(EgVkPhysicalDeviceFeature_geometryShader);
ECS_DECLARE(EgVkPhysicalDeviceFeature_tessellationShader);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sampleRateShading);
ECS_DECLARE(EgVkPhysicalDeviceFeature_dualSrcBlend);
ECS_DECLARE(EgVkPhysicalDeviceFeature_logicOp);
ECS_DECLARE(EgVkPhysicalDeviceFeature_multiDrawIndirect);
ECS_DECLARE(EgVkPhysicalDeviceFeature_drawIndirectFirstInstance);
ECS_DECLARE(EgVkPhysicalDeviceFeature_depthClamp);
ECS_DECLARE(EgVkPhysicalDeviceFeature_depthBiasClamp);
ECS_DECLARE(EgVkPhysicalDeviceFeature_fillModeNonSolid);
ECS_DECLARE(EgVkPhysicalDeviceFeature_depthBounds);
ECS_DECLARE(EgVkPhysicalDeviceFeature_wideLines);
ECS_DECLARE(EgVkPhysicalDeviceFeature_largePoints);
ECS_DECLARE(EgVkPhysicalDeviceFeature_alphaToOne);
ECS_DECLARE(EgVkPhysicalDeviceFeature_multiViewport);
ECS_DECLARE(EgVkPhysicalDeviceFeature_samplerAnisotropy);
ECS_DECLARE(EgVkPhysicalDeviceFeature_textureCompressionETC2);
ECS_DECLARE(EgVkPhysicalDeviceFeature_textureCompressionASTC_LDR);
ECS_DECLARE(EgVkPhysicalDeviceFeature_textureCompressionBC);
ECS_DECLARE(EgVkPhysicalDeviceFeature_occlusionQueryPrecise);
ECS_DECLARE(EgVkPhysicalDeviceFeature_pipelineStatisticsQuery);
ECS_DECLARE(EgVkPhysicalDeviceFeature_vertexPipelineStoresAndAtomics);
ECS_DECLARE(EgVkPhysicalDeviceFeature_fragmentStoresAndAtomics);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderTessellationAndGeometryPointSize);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderImageGatherExtended);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageExtendedFormats);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageMultisample);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageReadWithoutFormat);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageWriteWithoutFormat);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderUniformBufferArrayDynamicIndexing);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderSampledImageArrayDynamicIndexing);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageBufferArrayDynamicIndexing);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageArrayDynamicIndexing);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderClipDistance);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderCullDistance);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderFloat64);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderInt64);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderInt16);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderResourceResidency);
ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderResourceMinLod);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseBinding);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyBuffer);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyImage2D);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyImage3D);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency2Samples);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency4Samples);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency8Samples);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency16Samples);
ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyAliased);
ECS_DECLARE(EgVkPhysicalDeviceFeature_variableMultisampleRate);
ECS_DECLARE(EgVkPhysicalDeviceFeature_inheritedQueries);




void EgVkPhysicaldevicefeaturesImport(ecs_world_t *world)
{
	ECS_MODULE(world, EgVkPhysicaldevicefeatures);
	ecs_set_name_prefix(world, "EgVk");

	//typedef struct VkPhysicalDeviceFeatures
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_robustBufferAccess);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_fullDrawIndexUint32);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_imageCubeArray);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_independentBlend);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_geometryShader);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_tessellationShader);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sampleRateShading);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_dualSrcBlend);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_logicOp);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_multiDrawIndirect);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_drawIndirectFirstInstance);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_depthClamp);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_depthBiasClamp);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_fillModeNonSolid);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_depthBounds);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_wideLines);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_largePoints);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_alphaToOne);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_multiViewport);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_samplerAnisotropy);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_textureCompressionETC2);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_textureCompressionASTC_LDR);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_textureCompressionBC);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_occlusionQueryPrecise);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_pipelineStatisticsQuery);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_vertexPipelineStoresAndAtomics);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_fragmentStoresAndAtomics);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderTessellationAndGeometryPointSize);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderImageGatherExtended);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderStorageImageExtendedFormats);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderStorageImageMultisample);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderStorageImageReadWithoutFormat);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderStorageImageWriteWithoutFormat);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderUniformBufferArrayDynamicIndexing);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderSampledImageArrayDynamicIndexing);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderStorageBufferArrayDynamicIndexing);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderStorageImageArrayDynamicIndexing);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderClipDistance);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderCullDistance);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderFloat64);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderInt64);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderInt16);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderResourceResidency);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_shaderResourceMinLod);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseBinding);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidencyBuffer);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidencyImage2D);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidencyImage3D);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidency2Samples);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidency4Samples);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidency8Samples);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidency16Samples);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_sparseResidencyAliased);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_variableMultisampleRate);
	ECS_TAG_DEFINE(world, EgVkPhysicalDeviceFeature_inheritedQueries);
}










