#pragma once

#include "flecs.h"
#include <vulkan/vulkan.h>

#ifdef __cplusplus
extern "C" {
#endif


//typedef struct VkPhysicalDeviceFeatures
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_robustBufferAccess);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_fullDrawIndexUint32);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_imageCubeArray);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_independentBlend);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_geometryShader);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_tessellationShader);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sampleRateShading);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_dualSrcBlend);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_logicOp);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_multiDrawIndirect);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_drawIndirectFirstInstance);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_depthClamp);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_depthBiasClamp);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_fillModeNonSolid);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_depthBounds);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_wideLines);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_largePoints);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_alphaToOne);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_multiViewport);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_samplerAnisotropy);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_textureCompressionETC2);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_textureCompressionASTC_LDR);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_textureCompressionBC);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_occlusionQueryPrecise);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_pipelineStatisticsQuery);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_vertexPipelineStoresAndAtomics);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_fragmentStoresAndAtomics);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderTessellationAndGeometryPointSize);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderImageGatherExtended);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageExtendedFormats);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageMultisample);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageReadWithoutFormat);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageWriteWithoutFormat);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderUniformBufferArrayDynamicIndexing);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderSampledImageArrayDynamicIndexing);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageBufferArrayDynamicIndexing);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderStorageImageArrayDynamicIndexing);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderClipDistance);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderCullDistance);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderFloat64);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderInt64);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderInt16);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderResourceResidency);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_shaderResourceMinLod);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseBinding);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyBuffer);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyImage2D);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyImage3D);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency2Samples);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency4Samples);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency8Samples);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidency16Samples);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_sparseResidencyAliased);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_variableMultisampleRate);
extern ECS_DECLARE(EgVkPhysicalDeviceFeature_inheritedQueries);

void EgVkPhysicaldevicefeaturesImport(ecs_world_t *world);


#ifdef __cplusplus
}
#endif
