/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef DEMO_CANGUI1_BAKE_CONFIG_H
#define DEMO_CANGUI1_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <egcan.h>
#include <egimgui.h>
#include <egquantities.h>
#include <egspatials.h>
#include <egshapes.h>
#include <egcolors.h>
#include <sokol_app.h>
#include <sokol_log.h>
#include <sokol_gfx.h>
#include <sokol_glue.h>
#include <sokol_imgui.h>
#include <cimgui.h>

#endif

