/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef EGFSEPOLL_BAKE_CONFIG_H
#define EGFSEPOLL_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <EgFs.h>
#include <ecsx.h>
#include <flecs.h>

/* Convenience macro for exporting symbols */
#ifndef egfsepoll_STATIC
#if defined(egfsepoll_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define EGFSEPOLL_API __declspec(dllexport)
#elif defined(egfsepoll_EXPORTS)
  #define EGFSEPOLL_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define EGFSEPOLL_API __declspec(dllimport)
#else
  #define EGFSEPOLL_API
#endif
#else
  #define EGFSEPOLL_API
#endif

#endif

