/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef EGSPATIALSSYSTEMS_BAKE_CONFIG_H
#define EGSPATIALSSYSTEMS_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <egmath.h>

/* Convenience macro for exporting symbols */
#ifndef EgSpatialsSystems_STATIC
#if defined(EgSpatialsSystems_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define EGSPATIALSSYSTEMS_API __declspec(dllexport)
#elif defined(EgSpatialsSystems_EXPORTS)
  #define EGSPATIALSSYSTEMS_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define EGSPATIALSSYSTEMS_API __declspec(dllimport)
#else
  #define EGSPATIALSSYSTEMS_API
#endif
#else
  #define EGSPATIALSSYSTEMS_API
#endif

#endif

