/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef EGFSINOTIFY_BAKE_CONFIG_H
#define EGFSINOTIFY_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <EgFs.h>
#include <ecsx.h>
#include <flecs.h>

/* Convenience macro for exporting symbols */
#ifndef egfsinotify_STATIC
#if defined(egfsinotify_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define EGFSINOTIFY_API __declspec(dllexport)
#elif defined(egfsinotify_EXPORTS)
  #define EGFSINOTIFY_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define EGFSINOTIFY_API __declspec(dllimport)
#else
  #define EGFSINOTIFY_API
#endif
#else
  #define EGFSINOTIFY_API
#endif

#endif

